### PR TITLE
add consortia list

### PR DESCRIPTION
**Pull request by jharenza**
### Purpose

first draft of list!

### Issue

#141 

#### Which areas should receive a particularly close look?
NA

#### Is there anything that you want to discuss further?
no

#### Is the pull request ready for review?
yes

### Pull review checklist

Unless otherwise noted above, this PR will be considered ready for review when all four items have been checked.

- [x] All changes to text follow "one sentence per line" [[Manubot instructions](https://github.com/AlexsLemonade/OpenPBTA-manuscript/blob/master/USAGE.md#manubot-markdown)]
- [x] All citations follow the [Manubot citation instructions](https://github.com/AlexsLemonade/OpenPBTA-manuscript/blob/master/USAGE.md#citations)
- [x] All changes or additions to tables follow the [Manubot table instructions](https://github.com/AlexsLemonade/OpenPBTA-manuscript/blob/master/USAGE.md#tables)
- [x] All figures follow the [Manubot figure instructions](https://github.com/AlexsLemonade/OpenPBTA-manuscript/blob/master/USAGE.md#figures)
- [x] There are no new spelling errors identified by the [Manubot spellchecker](https://github.com/AlexsLemonade/OpenPBTA-manuscript/blob/master/USAGE.md#spellchecking)

### Spellcheck Step

The dictionary used for spellchecking can be updated.
Edit the file in `build/assets/custom-dictionary.txt` by adding new entries to the end.
You do not need to change anything else.
However, if you want to update the first line to have an accurate count of words and you want to remove non-unique ones, run the following command from within `build/assets` on your favorite OS X or Linux machine:
```
(( len = $(awk '!a[$0]++' < custom-dictionary.txt | wc -l ) - 1 )); tmpfile="$(mktemp)"; echo "personal_ws-1.1 en $len utf-8" > $tmpfile; tail -n +2 custom-dictionary.txt | awk '!a[$0]++' >> $tmpfile; mv $tmpfile custom-dictionary.txt
```

### CODE REVIEW

**Comment by jharenza** [comment]
@jaclyn-taroni just as an fyi, since adding the consortia people to the spelling check list, manubot now takes 2 hours to run - doesn't seem ideal, but wanted to give you a heads up in case you wanted to change anything

**Comment by sjspielman** [comment]
Hi @jharenza , it looks like each of the reference documents you linked to in issue #141 is protected (either within your CHOP login or private google sheet). I can't review this without having the correct info to compare against. Is there a way to link me in to at least the google sheet?

**Comment by jharenza** [comment]
Because of the length of time CI takes after adding this group, we will do this last.

**Comment by sjspielman** [comment]
Went ahead and updated to add `Pediatric`, and I also updated a few instances in the MS from `Neuro-oncology` --> `Neuro-Oncology` (as they use in https://pnoc.us/).

**Review by sjspielman — APPROVED** [review]
All good for whenever we want to merge!

**Pull request merged**
