### PR TITLE
add d3b and dbhi authors

### PR DESCRIPTION
**Pull request by jharenza**
adding v1 of author list

### Purpose

_Briefly describe your changes here._
Adding D3b and DBHI author list per #107 

### Issue

_What GitHub issue does your pull request address?_
#107 

#### Which areas should receive a particularly close look?
Should variables that are blank be left with each author and blank or should they be removed? I removed them for now.

#### Is there anything that you want to discuss further?
See above.

Re: spell check - it identified multiple errors due to github and twitter handles. Do we want to add these to the dictionary? I also noticed other errors in the report that were not in this PR - should we open a new ticket to fix these?

Also for now, I added @adamcresnick and myself last, thinking @cgreene and @jaclyn-taroni would be last last, but open to however we want to do this.

#### Is the pull request ready for review?
yes

### Pull review checklist

Unless otherwise noted above, this PR will be considered ready for review when all four items have been checked.

- [x] All changes to text follow "one sentence per line" [[Manubot instructions](https://github.com/AlexsLemonade/OpenPBTA-manuscript/blob/master/USAGE.md#manubot-markdown)]
- [x] All citations follow the [Manubot citation instructions](https://github.com/AlexsLemonade/OpenPBTA-manuscript/blob/master/USAGE.md#citations)
- [x] All changes or additions to tables follow the [Manubot table instructions](https://github.com/AlexsLemonade/OpenPBTA-manuscript/blob/master/USAGE.md#tables)
- [x] All figures follow the [Manubot figure instructions](https://github.com/AlexsLemonade/OpenPBTA-manuscript/blob/master/USAGE.md#figures)
- [x] There are no new spelling errors identified by the [Manubot spellchecker](https://github.com/AlexsLemonade/OpenPBTA-manuscript/blob/master/USAGE.md#spellchecking)

### Spellcheck Step

The dictionary used for spellchecking can be updated.
Edit the file in `build/assets/custom-dictionary.txt` by adding new entries to the end.
You do not need to change anything else.
However, if you want to update the first line to have an accurate count of words and you want to remove non-unique ones, run the following command from within `build/assets` on your favorite OS X or Linux machine:
```
(( len = $(awk '!a[$0]++' < custom-dictionary.txt | wc -l ) - 1 )); tmpfile="$(mktemp)"; echo "personal_ws-1.1 en $len utf-8" > $tmpfile; tail -n +2 custom-dictionary.txt | awk '!a[$0]++' >> $tmpfile; mv $tmpfile custom-dictionary.txt
```

### CODE REVIEW

**Comment by cgreene** [comment]
I have the ability to see the contributions of some but not all of these authors. Can you also update the contributor guidelines to note the procedure that you're using for authorship contributions that aren't apparent from github:
https://github.com/AlexsLemonade/OpenPBTA-manuscript/blob/master/CONTRIBUTING.md#authorship

This will keep our documentation in sync with our practices. Thanks!

**Comment by cgreene** [comment]
Oh! It also doesn't include CRediT (I missed this in https://github.com/AlexsLemonade/OpenPBTA-manuscript/pull/109 too). I need to update mine, and can you also update yours with the info (an example is here https://github.com/greenelab/covid19-review/blob/master/content/metadata.yaml#L17 ).

**Comment by jharenza** [comment]
> Oh! It also doesn't include CRediT (I missed this in #109 too). I need to update mine, and can you also update yours with the info (an example is here https://github.com/greenelab/covid19-review/blob/master/content/metadata.yaml#L17 ).

Oh yes, I was wondering where that fits in - didn't see in the example. I will add, thanks!

**Comment by cgreene** [comment]
Screen Shot 2020-08-26 at 7 15 25 AM

Appears to have worked! I'm going to approve. @jharenza , then you can check the output and make sure it looks like you expected and we can merge

**Comment by jharenza** [comment]
Just deleted the extra "Miguel" entries and now it looks good.

**Pull request merged**
