### PR TITLE
updated somatic cnv calling citation

### PR DESCRIPTION
**Pull request by wongjessica93**

### CODE REVIEW

**Comment by cgreene** [comment]
Actually `[@doi.org:10.1371/journal.pcbi.1004873]` should be `[@doi:10.1371/journal.pcbi.1004873]`

**Comment by migbro** [comment]
Yup, I see what I did wrong.  So, that works with shortdoi: doi:10/c9pd, for a final citation of [@doi:10/c9pd]

**Comment by cgreene** [comment]
I don't usually use short DOIs so not sure how the conversion generally works, but the build error is:
```
Error in expand_short_doi for 10/c9pd3 due to a ValueError:
```
Looks like it's not resolving.

**Comment by migbro** [comment]
So weird!  it's recommended in the manubot usage, and the site says "This shortcut will return the same results as http://dx.doi.org/10.1371/journal.pcbi.1004873, and doi:10/c9pd can be used in place of doi:10.1371/journal.pcbi.1004873."
Regardless, @wongjessica93 just go with how Casey had it formatted. Thanks!

**Comment by cgreene** [comment]
Let me ping @dhimmel to see if this is a useful bug report. If so, we can report it over in the manubot repo.

**Comment by dhimmel** [comment]
> Let me ping @dhimmel to see if this is a useful bug report. If so, we can report it over in the manubot repo.

The [build logs](https://travis-ci.com/AlexsLemonade/OpenPBTA-manuscript/builds/124264755) provide a sufficiently informative message for the initial citation of `@doi.org:10.1371/journal.pcbi.1004873`:

```
## ERROR
Invalid citation: doi.org:10.1371/journal.pcbi.1004873
Source "doi.org" is not valid.
Valid citation sources are {arxiv, doi, isbn, pmcid, pmid, raw, tag, url, wikidata}
```

The shortDOI of `10/c9pd3` is not actually valid, as you can see by trying to go to https://doi.org/10/c9pd3. I re-shortened the DOI and see that the issue is due to a `3` accidentally getting appended to http://doi.org/c9pd.

**Comment by cgreene** [comment]
Good 👀 @dhimmel. I missed the mismatch there!

P.S. I really wanted to say - good D-O-Eyes, but I thought it was too much. But not too much for a post script.

**Pull request merged**
