### PR TITLE
Jashapiro/cite updates

### LINKED ISSUE #304: Convert reference style to Cell format
#### What section of the manuscript should be updated?

References should be formatted for _Cell_ prior to submission

#### Proposed changes

This [page](https://github.com/manubot/manufesto/blob/master/USAGE.md#custom-formatting) describes how to update references to a specific citation style, specifically, [this](https://github.com/manubot/rootstock/issues/242#issuecomment-507688339) comment.

Looks like the _Cell_ citation style can be found [here](https://github.com/citation-style-language/styles/blob/master/cell.csl) or [here](https://www.zotero.org/styles?q=Cell&dependent=0).

### LINKED ISSUE #305: Update biorxiv references and others with incomplete info
Some of the papers we cited as preprints are now available as published papers, so we should go through and update those that have been. 

We can find the biorxiv papers because they should all contain the  doi prefix `10.1101`. 

Those that are still only on biorxiv should be updated to use the `@https://doi.org/` reference style to get the "journal" properly set, as per  https://github.com/manubot/rootstock/blob/main/USAGE.md#citations and https://github.com/manubot/manubot/issues/16

There may be other references with incomplete information. We can resolve these by manually adding information to `manual-references.json`

### PR DESCRIPTION
**Pull request by jashapiro**
This PR sets the citation style to `Cell`, which should make the references a bit easier for people to track when reviewing.

When I did this, I noticed that bioRxiv refs were not rendering with full info, so I tried a few different manubot citation formats, but couldn't get anything to work. I end up adding manual entries for the bioRxiv references, and left them with the (new) `@biorxiv:` citation format, which may be nice for clarity and future tracking.

There was also at least one bioRxiv citation that has since been published, so that is updated as well. 

Finally, there were a couple of places that I noticed we cited the same paper twice in consecutive sentences. I combined those citations and moved them to the end of the second sentence.

Please look both at the markdown updates and the output file, and check that all references have the expected format and content!

Closes #304 
Closes #305

### CODE REVIEW

**Review by jharenza — COMMENTED** [review]
The changes in the MD files look good, but I do not see a manubot output on this PR, maybe because it was stacked initially? Can you commit an update to trigger the appveyor?

**Comment by jashapiro** [comment]
@jharenza Should be good to go now.

**Review by jharenza — COMMENTED** [review]
Hi @jashapiro - these changes look good. The Cell format and biorxiv changes look as expected.

I did notice some other refs we will want to update, but do not need to do it here and I can put this into a new ticket. Perhaps, if any, you can update the two arxiv references here.

https://paperpile.com/s/cell-citation-style/


- Website link only - I think this one should possibly be a link within the text
PNOC008: A Pilot Trial Testing the Clinical Benefit of Using Molecular Profiling to Determine an Individualized Treatment Plan in Children and Young Adults with High Grade Glioma (Excluding Diffuse Intrinsic Pontine Glioma) – Pacific Pediatric Neuro-Oncology Consortium.

- Author to add: `National Cancer Institute`
(2008). Childhood Medulloblastoma and Other Central Nervous System Embryonal Tumors Treatment (PDQ®)–Health Professional Version - NCI.

- Author to add: `The St. Jude Children's Research Hospital–Washington University Pediatric Cancer Genome Project.`
(2014). The genomic landscape of diffuse intrinsic pontine glioma and pediatric non-brainstem high-grade glioma. Nat Genet 46, 444–450. https://doi.org/10.1038/ng.2938.

- `NA` author, remove NA
&NA; (2012). FDA Approves Pediatric Formulation of Afinitor for Children with Subependymal Giant Cell Astrocytoma. Oncology Times 34, 22. https://doi.org/10.1097/01.cot.0000421359.88140.a8.

- Should these have titles un-hyperlinked and have direct web links if a website and not a paper?? Assuming this happens if we did not use doi
  - Boettiger, C., and Eddelbuettel, D. (2017). An Introduction to Rocker: Docker Containers for R (arXiv).
  - Li, H. (2013). Aligning sequence reads, clone sequences and assembly contigs with BWA-MEM (arXiv).
  - Mantel, N. (1966). Evaluation of survival data and two new rank order statistics arising in its consideration. Cancer Chemother Rep 50, 163–170.
  - Merkel, D. (2014). Docker: lightweight Linux containers for consistent development and deployment. Linux Journal 2014, 2:2.
  - Parker, H. (2017). Opinionated analysis development (PeerJ).
  - Research, C. for D.E. and (2018). FDA approves everolimus for tuberous sclerosis complex-associated partial-onset seizures. FDA.
  - Research, C. for D.E. and (2019a). FDA approves larotrectinib for solid tumors with NTRK gene fusions. FDA.
  - Research, C. for D.E. and (2019b). FDA approves entrectinib for NTRK solid tumors and ROS-1 NSCLC. FDA.
  - Research, C. for D.E. and (2020a). FDA approves pembrolizumab for adults and children with TMB-H solid tumors. FDA.
  - Research, C. for D.E. and (2020b). FDA approves selumetinib for neurofibromatosis type 1 with symptomatic, inoperable plexiform neurofibromas. FDA.
bio

- A few refs have html italic/superscript tags, not sure if that is an issue, just pointing out here:
  - Duchemann, B., Naigeon, M., Auclin, E., Ferrara, R., Cassard, L., Jouniaux, J.-M., Boselli, L., Grivel, J., Desnoyer, A., Danlos, F.-X., et al. (2022). CD8<sup>+</sup>PD-1<sup>+</sup> to CD4<sup>+</sup>PD-1<sup>+</sup> ratio (PERLS) is associated with prognosis of patients with advanced NSCLC treated with PD-(L)1 blockers. J Immunother Cancer 10, e004012. https://doi.org/10.1136/jitc-2021-004012.
  - Guha, T., and Malkin, D. (2017). Inherited<i>TP53</i>Mutations and the Li–Fraumeni Syndrome. Cold Spring Harb Perspect Med 7, a026187. https://doi.org/10.1101/cshperspect.a026187.
  - Pfaff, E., Remke, M., Sturm, D., Benner, A., Witt, H., Milde, T., von Bueren, A.O., Wittmann, A., Schöttler, A., Jorch, N., et al. (2010). <i>TP53</i> Mutation Is Frequently Associated With <i>CTNNB1</i> Mutation or <i>MYCN</i> Amplification and Is Compatible With Long-Term Survival in Medulloblastoma. JCO 28, 5188–5196. https://doi.org/10.1200/jco.2010.31.1670.
  - Ramkissoon, L.A., Horowitz, P.M., Craig, J.M., Ramkissoon, S.H., Rich, B.E., Schumacher, S.E., McKenna, A., Lawrence, M.S., Bergthold, G., Brastianos, P.K., et al. (2013). Genomic analysis of diffuse pediatric low-grade gliomas identifies recurrent oncogenic truncating rearrangements in the transcription factor <i>MYBL1</i>. Proc. Natl. Acad. Sci. U.S.A. 110, 8188–8193. https://doi.org/10.1073/pnas.1300252110.

- This one has some odd author attributes, probably needs a manual update
Justin Guinney [Aut, Cre], Robert Castelo [Aut], Joan Fernandez[Ctb] (2017). GSVA. https://doi.org/10.18129/b9.bioc.gsva.

**Comment by jashapiro** [comment]
> Should these have titles un-hyperlinked and have direct web links if a website and not a paper?? Assuming this happens if we did not use doi
> 
> * Boettiger, C., and Eddelbuettel, D. (2017). An Introduction to Rocker: Docker Containers for R (arXiv).
> * Li, H. (2013). Aligning sequence reads, clone sequences and assembly contigs with BWA-MEM (arXiv).
> * Mantel, N. (1966). Evaluation of survival data and two new rank order statistics arising in its consideration. Cancer Chemother Rep 50, 163–170.
> * Merkel, D. (2014). Docker: lightweight Linux containers for consistent development and deployment. Linux Journal 2014, 2:2.
> * Parker, H. (2017). Opinionated analysis development (PeerJ).
> * Research, C. for D.E. and (2018). FDA approves everolimus for tuberous sclerosis complex-associated partial-onset seizures. FDA.
> * Research, C. for D.E. and (2019a). FDA approves larotrectinib for solid tumors with NTRK gene fusions. FDA.
> * Research, C. for D.E. and (2019b). FDA approves entrectinib for NTRK solid tumors and ROS-1 NSCLC. FDA.
> * Research, C. for D.E. and (2020a). FDA approves pembrolizumab for adults and children with TMB-H solid tumors. FDA.
> * Research, C. for D.E. and (2020b). FDA approves selumetinib for neurofibromatosis type 1 with symptomatic, inoperable plexiform neurofibromas. FDA.
>   bio

The first few are articles, so I will leave them as they are. I can see what happens with the FDA approvals if I change it to an `@url` reference, but we might have to do that manually somehow.

 

> * `NA` author, remove NA
>   &NA; (2012). FDA Approves Pediatric Formulation of Afinitor for Children with Subependymal Giant Cell Astrocytoma. Oncology Times 34, 22. https://doi.org/10.1097/01.cot.0000421359.88140.a8.

Should we change this to link to an FDA page as well, for consistency? Or can we cite all of these from a meta-source like https://www.fda.gov/about-fda/oncology-center-excellence/pediatric-oncology-drug-approvals?

I think these FDA approval citations make sense as a separate issue.

I'll look into the rest on Monday.

**Comment by jashapiro** [comment]
> * This one has some odd author attributes, probably needs a manual update
>   Justin Guinney [Aut, Cre], Robert Castelo [Aut], Joan Fernandez[Ctb] (2017). GSVA. https://doi.org/10.18129/b9.bioc.gsva.

Removing this one, as it is cited separately with a paper as it should be.

**Comment by jashapiro** [comment]
> Author to add: The St. Jude Children's Research Hospital–Washington University Pediatric Cancer Genome Project.
(2014). The genomic landscape of diffuse intrinsic pontine glioma and pediatric non-brainstem high-grade glioma. Nat Genet 46, 444–450. https://doi.org/10.1038/ng.2938.

When I download the citation link on this page, I get the author list that we are using here, so I don't think we need to change this.

**Comment by jharenza** [comment]
> > Author to add: The St. Jude Children's Research Hospital–Washington University Pediatric Cancer Genome Project.
> > (2014). The genomic landscape of diffuse intrinsic pontine glioma and pediatric non-brainstem high-grade glioma. Nat Genet 46, 444–450. https://doi.org/10.1038/ng.2938.
> 
> When I download the citation link on this page, I get the author list that we are using here, so I don't think we need to change this. (this is also the author list on pubmed: https://pubmed.ncbi.nlm.nih.gov/24705251/)

oh I meant to break that up - the citation we have starts with (2014) with no authors.

**Comment by jashapiro** [comment]
> > > Author to add: The St. Jude Children's Research Hospital–Washington University Pediatric Cancer Genome Project.
> > > (2014). The genomic landscape of diffuse intrinsic pontine glioma and pediatric non-brainstem high-grade glioma. Nat Genet 46, 444–450. https://doi.org/10.1038/ng.2938.
> > 
> > 
> > When I download the citation link on this page, I get the author list that we are using here, so I don't think we need to change this. (this is also the author list on pubmed: https://pubmed.ncbi.nlm.nih.gov/24705251/)
> 
> oh I meant to break that up - the citation we have starts with (2014) with no authors.

In the version I am looking at, this paper is listed with the following authors: 
> Wu, G., Diaz, A.K., Paugh, B.S., Rankin, S.L., Ju, B., Li, Y., Zhu, X., Qu, C., Chen, X., Zhang, J., et al. (2014)

**Review by jharenza — APPROVED** [review]
This looks good, and the remaining ones in #310 can be addressed in a separate PR as discussed.

**Pull request merged**
