### PR TITLE
fix chimerDB doi

### PR DESCRIPTION
**Pull request by jharenza**
wasn't formatting the reference properly

### CODE REVIEW

**Comment by cgreene** [comment]
The short DOI will just look up the long DOI. I don't expect this will change the behavior. Short DOIs are a way to get around disallowed characters, but this doesn't have one.

Unfortunately it looks like NAR/OUP has entered the wrong information into crossref:
https://search.crossref.org/?q=10.1093%2Fnar%2Fgkw1083

The course to get it fixed would be to to report it to NAR. I'll tweet at them.

**Comment by jharenza** [comment]
Ahh, you are all so DOI-savvy!

**Comment by cgreene** [comment]
https://twitter.com/GreeneScientist/status/1164880540425568256?s=20

**Comment by cgreene** [comment]
I'm going to close this PR but open an issue to track this.

**Pull request closed without merging**
