### PR TITLE
Incorporate Table S2

### LINKED ISSUE #415: Update Table S2 caption
Once https://github.com/AlexsLemonade/OpenPBTA-analysis/pull/1689 is done, there will be an additional sheet in S2 that will need to be described in its caption.

### PR DESCRIPTION
**Pull request by sjspielman**
Closes #415 

This PR makes a couple updates now that we've updated Table S2:

- Reference the table in the oncoprint results, in particular for ATRT. I don't actually think we need to explain _why_ the result is in Table S2 and not Figure 2 since I added an overall sentence that all results are in Table S2!
- Fix DOI discussed here: https://github.com/AlexsLemonade/OpenPBTA-manuscript/pull/414#discussion_r1117712372
- Update Table S2 caption with fourth sheet information
- ~[forthcoming]~ Completed! Update Table S2 hash in link

### CODE REVIEW

**Comment by sjspielman** [comment]
@jharenza This PR is set except for the hash, which I'm keeping tabs on, if you wanted to look before it's officially ready for review.

**Comment by sjspielman** [comment]
This is now ready for formal review. In https://github.com/AlexsLemonade/OpenPBTA-manuscript/pull/416/commits/3e3b685faee9286bf0c92808731d59b9aa5b7c2b, I updated the Table S2 link, and since the other supp tables were technically updated in that commit (although content was unchanged, they were rengenerated) I went ahead and did those to. I can revert those lines though if we prefer.

**Review by jharenza — APPROVED** [review]
Can you just update the hashes in all figures for the results file, too?

**Comment by sjspielman** [comment]
@jharenza To clarify, do you mean for all hashes to be the same across all figures/tables? Currently everything seems to be linked to a most recent version, even if not the same link.

**Comment by jaclyn-taroni** [comment]
> Yes! I think this is the last analysis so we can sync all now.

I think I can manually trigger the git contributions/author order workflow in that case.

**Comment by jharenza** [comment]
looks good!

**Pull request merged**
