### PR TITLE
Add supp table descriptions to 07.supplemental.md

### PR DESCRIPTION
**Pull request by jharenza**
### Purpose
❗ Merge #202  first.

Add supplemental table descriptions to the supplemental info section.

#212 

### Directions for reviewers. Tell potential reviewers what kind of feedback you are soliciting.
This is also updated assuming https://github.com/AlexsLemonade/OpenPBTA-analysis/issues/1260 goes in with these changes.

#### Is there anything that you want to discuss further?
This section will need formatting removed once converted to pandoc (eg the figures are linked and when we submit, this will go away). Do we want to remove this from the supp figures/tables? Right now, they are not numbered appropriately anyway (see #172). If yes, I can go through the text and remove the links within this PR.

For the supplemental 
#### Is the pull request ready for review?
no

### Pull review checklist

Unless otherwise noted above, this PR will be considered ready for review when all four items have been checked.

- [x] All changes to text follow "one sentence per line" [[Manubot instructions](https://github.com/AlexsLemonade/OpenPBTA-manuscript/blob/master/USAGE.md#manubot-markdown)]
- [x] All citations follow the [Manubot citation instructions](https://github.com/AlexsLemonade/OpenPBTA-manuscript/blob/master/USAGE.md#citations)
- [x] All changes or additions to tables follow the [Manubot table instructions](https://github.com/AlexsLemonade/OpenPBTA-manuscript/blob/master/USAGE.md#tables)
- [x] All figures follow the [Manubot figure instructions](https://github.com/AlexsLemonade/OpenPBTA-manuscript/blob/master/USAGE.md#figures)
- [x] There are no new spelling errors identified by the [Manubot spellchecker](https://github.com/AlexsLemonade/OpenPBTA-manuscript/blob/master/USAGE.md#spellchecking)

### Spellcheck Step

The dictionary used for spellchecking can be updated.
Edit the file in `build/assets/custom-dictionary.txt` by adding new entries to the end.
You do not need to change anything else.
However, if you want to update the first line to have an accurate count of words and you want to remove non-unique ones, run the following command from within `build/assets` on your favorite OS X or Linux machine:
```
(( len = $(awk '!a[$0]++' < custom-dictionary.txt | wc -l ) - 1 )); tmpfile="$(mktemp)"; echo "personal_ws-1.1 en $len utf-8" > $tmpfile; tail -n +2 custom-dictionary.txt | awk '!a[$0]++' >> $tmpfile; mv $tmpfile custom-dictionary.txt
```

### CODE REVIEW

**Comment by sjspielman** [comment]
Quick note, this is still blocked from [#1260](https://github.com/AlexsLemonade/OpenPBTA-analysis/issues/1260), but not sure that is still intentional.

**Comment by jharenza** [comment]
> Quick note, this is still blocked from [#1260](https://github.com/AlexsLemonade/OpenPBTA-analysis/issues/1260), but not sure that is still intentional.

Ah, @runjin326 will be working on that one today. I blocked it so we would have the tables updated when the text updates, so I guess we can have this ready for when that happens?

**Comment by jharenza** [comment]
@sjspielman 1260 is now in, so this is unblocked!

**Review by sjspielman — APPROVED** [review]
👍

**Pull request merged**
