### PR TITLE
Final touches to references & key resources

### LINKED ISSUE #358: Remove html tags from references
Originally noted by @jharenza in  https://github.com/AlexsLemonade/OpenPBTA-manuscript/issues/310:
> A few refs have html italic/superscript tags, not sure if that is an issue, just pointing out here:
>
> * Duchemann, B., Naigeon, M., Auclin, E., Ferrara, R., Cassard, L., Jouniaux, J.-M., Boselli, L., Grivel, J., Desnoyer, A., Danlos, F.-X., et al. (2022). CD8+PD-1+ to CD4+PD-1+ ratio (PERLS) is associated with prognosis of patients with advanced NSCLC treated with PD-(L)1 blockers. J Immunother Cancer 10, e004012. https://doi.org/10.1136/jitc-2021-004012.
> * Guha, T., and Malkin, D. (2017). InheritedTP53Mutations and the Li–Fraumeni Syndrome. Cold Spring Harb Perspect Med 7, a026187. https://doi.org/10.1101/cshperspect.a026187.
> * Pfaff, E., Remke, M., Sturm, D., Benner, A., Witt, H., Milde, T., von Bueren, A.O., Wittmann, A., Schöttler, A., Jorch, N., et al. (2010). TP53 Mutation Is Frequently Associated With CTNNB1 Mutation or MYCN Amplification and Is Compatible With Long-Term Survival in Medulloblastoma. JCO 28, 5188–5196. https://doi.org/10.1200/jco.2010.31.1670.
> * Ramkissoon, L.A., Horowitz, P.M., Craig, J.M., Ramkissoon, S.H., Rich, B.E., Schumacher, S.E., McKenna, A., Lawrence, M.S., Bergthold, G., Brastianos, P.K., et al. (2013). Genomic analysis of diffuse pediatric low-grade gliomas identifies recurrent oncogenic truncating rearrangements in the transcription factor MYBL1. Proc. Natl. Acad. Sci. U.S.A. 110, 8188–8193. https://doi.org/10.1073/pnas.1300252110.

While we can fix these with manual references, it is probably just as easy to make the fix in the final submission document(s), which would allow us to add back the formatting that the html tags were trying to implement.

### LINKED ISSUE #458: Final touches to references
- [ ] Make sure all references in the Key Resources Table are in the main reference list 
- [ ] Change CSL to <https://www.zotero.org/styles/cell-genomics> https://github.com/AlexsLemonade/OpenPBTA-manuscript/blob/93aa068064f5187c1de57d5d53154c1f7702efcf/build/pandoc/defaults/common.yaml#L12
- [ ] Any manual fixes to reference lists (related: #358)

### PR DESCRIPTION
**Pull request by jashapiro**
### Purpose

Trying to finalize references for publication.

Here I added a large number of manual references to clean up the final reference list. The main things that required manual references were to remove any HTML tags that snuck into automatically generated references, as well as adding missing page numbers in a number of cases. 

I also updated to the cell genomics CSL file, which I think is the same as what we had before, but good to use the official one.

Finally, I made a few updates to the Key Resources table, adding in some headers that I thought were missing and adding references in a few places. While I was there I tried to follow the instructions at https://www.elsevier.com/authors/tools-and-resources/key-resources-table, which also meant that I added `Cat#` to many of the items in the table.

(Oh, and updates to the metadata that are just making all affiliations lists to get manubot to complain a bit less)

### Issue

closes #458
closes #358

#### Which areas should receive a particularly close look?

I think the main thing to look at is the generated reference section, as that is where the results of my changes will ultimately show up. I think I caught all of the places where a page or article number was missing, but please check if there are any that I missed! 

There are a couple from Frontiers journals that remain without page numbers because in looking at the referenced pages there was no value I could find to use.

#### Is there anything that you want to discuss further?

Please do look at the reference formats in general: are there any that we think require different information? I may be able to massage things into the correct format if we want to get more customized.

#### Is the pull request ready for review?

Yes

### Pull review checklist

Unless otherwise noted above, this PR will be considered ready for review when all four items have been checked.

- [x] All changes to text follow "one sentence per line" [[Manubot instructions](https://github.com/AlexsLemonade/OpenPBTA-manuscript/blob/master/USAGE.md#manubot-markdown)]
- [x] All citations follow the [Manubot citation instructions](https://github.com/AlexsLemonade/OpenPBTA-manuscript/blob/master/USAGE.md#citations)
- [x] All changes or additions to tables follow the [Manubot table instructions](https://github.com/AlexsLemonade/OpenPBTA-manuscript/blob/master/USAGE.md#tables)
- [x] All figures follow the [Manubot figure instructions](https://github.com/AlexsLemonade/OpenPBTA-manuscript/blob/master/USAGE.md#figures)
- [x] There are no new spelling errors identified by the [Manubot spellchecker](https://github.com/AlexsLemonade/OpenPBTA-manuscript/blob/master/USAGE.md#spellchecking)

### Spellcheck Step

The dictionary used for spellchecking can be updated.
Edit the file in `build/assets/custom-dictionary.txt` by adding new entries to the end.
You do not need to change anything else.
However, if you want to update the first line to have an accurate count of words and you want to remove non-unique ones, run the following command from within `build/assets` on your favorite OS X or Linux machine:
```
(( len = $(awk '!a[$0]++' < custom-dictionary.txt | wc -l ) - 1 )); tmpfile="$(mktemp)"; echo "personal_ws-1.1 en $len utf-8" > $tmpfile; tail -n +2 custom-dictionary.txt | awk '!a[$0]++' >> $tmpfile; mv $tmpfile custom-dictionary.txt
```

### CODE REVIEW

**Comment by jharenza** [comment]
hey @jashapiro. Thanks for working on these! I took some notes on the following which still render:


**Missing journal name**
Commissioner, O. of the (2023). Pediatric Oncology Drug Approvals. FDA. - possibly we should spell out FDA
Parker, H. (2017). Opinionated analysis development. 10.7287/peerj.preprints.3210v1. - needs journal name, on website citation looks like: "Parker H. 2017. Opinionated analysis development. PeerJ Preprints 5:e3210v1 https://doi.org/10.7287/peerj.preprints.3210v1"

McInnes, L., Healy, J., and Melville, J. (2020). UMAP: Uniform Manifold Approximation and Projection for Dimension Reduction. 10.48550/arXiv.1802.03426.


**arxiv probably shouldn't be in parentheses**
Li, H. (2013). Aligning sequence reads, clone sequences and assembly contigs with BWA-MEM (arXiv).
Boettiger, C., and Eddelbuettel, D. (2017). An Introduction to Rocker: Docker Containers for R (arXiv).

**missing the volume and pages**
Kline, C., Jain, P., Kilburn, L., Bonner, E.R., Gupta, N., Crawford, J.R., Banerjee, A., Packer, R.J., Villanueva-Meyer, J., Luks, T., et al. (2022). Upfront Biology-Guided Therapy in Diffuse Intrinsic Pontine Glioma: Therapeutic, Molecular, and Biomarker Outcomes from PNOC003. Clinical Cancer Research, OF1–OF14. 10.1158/1078-0432.ccr-22-0803.

should have "Clin Cancer Res (2022) 28 (18): 3965–3978."

**has "&amp;"**
Surrey, L.F., Jain, P., Zhang, B., Straka, J., Zhao, X., Harding, B.N., Resnick, A.C., Storm, P.B., Buccoliero, A.M., Genitori, L., et al. (2019). Genomic Analysis of Dysembryoplastic Neuroepithelial Tumor Spectrum Reveals a Diversity of Molecular Alterations Dysregulating the MAPK and PI3K/mTOR Pathways. Journal of Neuropathology &amp; Experimental Neurology 78, 1100–1111. 10.1093/jnen/nlz101.


**Have html tags:**
Sievers, P., Sill, M., Schrimpf, D., Stichel, D., Reuss, D.E., Sturm, D., Hench, J., Frank, S., Krskova, L., Vicha, A., et al. (2020). A subset of pediatric-type thalamic gliomas share a distinct DNA methylation profile, H3K27me3 loss and frequent alteration of <i>EGFR</i>. Neuro-Oncology 23, 34–43. 10.1093/neuonc/noaa251.

Pfaff, E., Remke, M., Sturm, D., Benner, A., Witt, H., Milde, T., von Bueren, A.O., Wittmann, A., Schöttler, A., Jorch, N., et al. (2010). <i>TP53</i> Mutation Is Frequently Associated With <i>CTNNB1</i> Mutation or <i>MYCN</i> Amplification and Is Compatible With Long-Term Survival in Medulloblastoma. JCO 28, 5188–5196. 10.1200/jco.2010.31.1670.

Duchemann, B., Naigeon, M., Auclin, E., Ferrara, R., Cassard, L., Jouniaux, J.-M., Boselli, L., Grivel, J., Desnoyer, A., Danlos, F.-X., et al. (2022). CD8<sup>+</sup>PD-1<sup>+</sup> to CD4<sup>+</sup>PD-1<sup>+</sup> ratio (PERLS) is associated with prognosis of patients with advanced NSCLC treated with PD-(L)1 blockers. J Immunother Cancer 10, e004012. 10.1136/jitc-2021-004012.

Ramkissoon, L.A., Horowitz, P.M., Craig, J.M., Ramkissoon, S.H., Rich, B.E., Schumacher, S.E., McKenna, A., Lawrence, M.S., Bergthold, G., Brastianos, P.K., et al. (2013). Genomic analysis of diffuse pediatric low-grade gliomas identifies recurrent oncogenic truncating rearrangements in the transcription factor <i>MYBL1</i>. Proc. Natl. Acad. Sci. U.S.A. 110, 8188–8193. 10.1073/pnas.1300252110.

Cobrinik, D., Ostrovnaya, I., Hassimi, M., Tickoo, S.K., Cheung, I.Y., and Cheung, N.-K.V. (2013). Recurrent pre-existing and acquired DNA copy number alterations, including focal<i>TERT</i>gains, in neuroblastoma central nervous system metastases. Genes Chromosomes Cancer 52, 1150–1166. 10.1002/gcc.22110.

Burel‐Vandenbos, F., Pierron, G., Thomas, C., Reynaud, S., Gregoire, V., Duhil de Benaze, G., Croze, S., Chivoret, N., Honavar, M., Figarella‐Branger, D., et al. (2020). A polyphenotypic malignant paediatric brain tumour presenting a <i>MN1‐PATZ1</i> fusion, no epigenetic similarities with CNS High‐Grade Neuroepithelial Tumour with <i>MN1</i> Alteration (CNS HGNET‐MN1) and related to <i>PATZ1</i> ‐fused sarcomas. Neuropathol Appl Neurobiol 46, 506–509. 10.1111/nan.12626.

Guha, T., and Malkin, D. (2017). Inherited<i>TP53</i>Mutations and the Li–Fraumeni Syndrome. Cold Spring Harb Perspect Med 7, a026187. 10.1101/cshperspect.a026187.

**has "npj" in here which probably shouldn't be**
Bi, W.L., Greenwald, N.F., Abedalthagafi, M., Wala, J., Gibson, W.J., Agarwalla, P.K., Horowitz, P., Schumacher, S.E., Esaulova, E., Mei, Y., et al. (2017). Genomic landscape of high-grade meningiomas. npj Genomic Med 2. 10.1038/s41525-017-0014-7.

**Comment by jashapiro** [comment]
> hey @jashapiro. Thanks for working on these! I took some notes on the following which still render:

Aaah! I pushed a version with a broken json file, so all my customization is missing! Pushing the hopefully fixed version now.

**Comment by jashapiro** [comment]
> **has "npj" in here which probably shouldn't be**
> Bi, W.L., Greenwald, N.F., Abedalthagafi, M., Wala, J., Gibson, W.J., Agarwalla, P.K., Horowitz, P., Schumacher, S.E., Esaulova, E., Mei, Y., et al. (2017). Genomic landscape of high-grade meningiomas. npj Genomic Med 2. 10.1038/s41525-017-0014-7.

This one is actually correct! See https://www.nature.com/articles/s41525-017-0014-7#citeas

**Comment by jashapiro** [comment]
Okay @jharenza, all of those should now be fixed, plus one ref that for some reason wasn't being fetched properly in the automated build (but worked fine locally). Sorry for the trouble! 

I think I caught everything now, but the last version is still rebuilding. 

(JSON really shouldn't fail with a trailing comma, but it does, so I should have caught it!)

**Review by jharenza — APPROVED** [review]
This looks good now!!

**Pull request merged**
