### PR TITLE
Adding CCDL contributors

### PR DESCRIPTION
**Pull request by jaclyn-taroni**
### Purpose

Addresses #110. We're using a broad definition of `Investigation` and a narrow definition of `Software` per https://github.com/AlexsLemonade/OpenPBTA-manuscript/issues/110#issuecomment-689024001 in these changes. I've filed #116 and #117 so we can continue the discussion about those roles, specifically.

#### Which areas should receive a particularly close look?

@jashapiro @cansavvy  and @cbethell  can you carefully review your contact information please?

#### Is there anything that you want to discuss further?

#116 and #117 are better spots for the remaining discussion points I had, as they will impact entries other than what is being added here.

#### Is the pull request ready for review?

Yes.

### Spellcheck Step

The dictionary used for spellchecking can be updated.
Edit the file in `build/assets/custom-dictionary.txt` by adding new entries to the end.
You do not need to change anything else.
However, if you want to update the first line to have an accurate count of words and you want to remove non-unique ones, run the following command from within `build/assets` on your favorite OS X or Linux machine:
```
(( len = $(awk '!a[$0]++' < custom-dictionary.txt | wc -l ) - 1 )); tmpfile="$(mktemp)"; echo "personal_ws-1.1 en $len utf-8" > $tmpfile; tail -n +2 custom-dictionary.txt | awk '!a[$0]++' >> $tmpfile; mv $tmpfile custom-dictionary.txt
```

### CODE REVIEW

**Comment by jashapiro** [comment]
My record looks good. My only question is whether we should all list ALSF as a funder? Right now only @jaclyn-taroni has it listed, but it would seem that it should apply to all or none of the CCDL folks? Or was @jaclyn-taroni funded for this project before she joined CCDL full time?

**Comment by jaclyn-taroni** [comment]
@jashapiro - thank you, I forgot to bring that up. @cgreene is funded via an ALSF grant, ALSF employees are funded by ALSF but not through a grant. I agree that for ALSF employees it is all or nothing, I just forgot.

**Comment by cgreene** [comment]
I think it's probably worth having all list it. Especially since I have to list the COI.

**Comment by jaclyn-taroni** [comment]
Added ALSF as a funder for all the ALSF employees in https://github.com/AlexsLemonade/OpenPBTA-manuscript/pull/118/commits/dc47c8adf5ef48fdefa0a4ee91077dc0586aeb15

**Comment by cbethell** [comment]
My record/contact information looks good in this PR 👍 .

**Comment by cansavvy** [comment]
Looks good to me!

**Review by jashapiro — APPROVED** [review]
:shipit:

**Pull request merged**
